---
- name: Deploy Scientific Calculator Docker Container
  hosts: localhost
  tasks:
    - name: Stop and remove any existing container
      community.docker.docker_container:
        name: "sci-calc"
        state: absent
        force_kill: yes

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: "dhruvk321/calculator-app:latest"
        source: pull

    - name: Run the application container in the background with interactive support
      community.docker.docker_container:
        name: "sci-calc"
        image: "dhruvk321/calculator-app:latest"
        state: started
        detach: yes
        tty: yes
        interactive: yes